### ISSUE TITLE
Token in URL allows trivial priv escalation

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/user_workspaces_server#55]
We connect to Jupyter using the information in the Jobs API response:
```
"url_path": "/passthrough/1605....36bd/51/lab?token=f90b....5f37",
```

This seems like a security problem: People are used to copy and pasting urls, but this URL grants access to the workspace, even to unauthenticated, unauthorized users.

Somewhat more secure approach would be to pass the token the body of a POST.

Juan disagrees:
> I don’t think that URL sharing expectation is one that we should support. Realistically, these sessions are their personal user sessions, they’re not meant to be shared.

**Comment by ngehlenborg** [comment]
If I understand this correctly, anyone sharing a link to a workspace (whether they do that on purpose or not is a different question) will give implicitly give access to any data that they uploaded into the workspace. Is that correct? 

If so, I think we need to find another solution for authentication.

**Comment by jpuerto-psc** [comment]
@mccalluc @ngehlenborg @pdblood:

**Solutions proposed**
- The token in the URL gets removed as soon as the user connects to JupyterLab, therefore, as long as the URL can't be copy/pasted from the workspaces UI (right clicking an anchor and copying the URL from there) users should not really be able to "share" their URLs. This is my preferred option as it does not require any major code changes from the workspaces and still follows Jupyter's suggestions.
 
- User is displayed a token from the UI, and they manually enter that token into the JupyterLab UI. This avoids some of the CSRF/XSRF concerns that @mccalluc mentioned. Not my favorite option as this might be clunky from a user perspective.

- The UI creates a form with the token hidden as a password. When the user clicks the button to access their session, it submits the form. This goes against CSRF/XSRF as Chuck pointed out. This might also break if JupyterLab changes their login page/routine at all. Sometimes fails due to `missing _xsrf` in the POST body (since this is only available from the Jupyter UI).

**Comment by jpuerto-psc** [comment]
@mccalluc @ngehlenborg @pdblood pinging to get discussion going on this issue.

**Comment by ngehlenborg** [comment]
I would be happy with the first proposed solution:
> The token in the URL gets removed as soon as the user connects to JupyterLab, therefore, as long as the URL can't be copy/pasted from the workspaces UI (right clicking an anchor and copying the URL from there) users should not really be able to "share" their URLs. This is my preferred option as it does not require any major code changes from the workspaces and still follows Jupyter's suggestions.

**Comment by mccalluc** [comment]
Ok: So instead of an actual link, it will be javascript that just sets the `location`.

**Comment by jpuerto-psc** [comment]
Sounds good - I will close the issue here with the understanding that remaining work will be on the front-end. Thanks!
